
name: chess_umbrella
description: Play chess with multipeer connectivity

version: 1.0.0+3

environment:
  sdk: ">=2.1.0 <3.0.0"


dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  tuple: ^1.0.2
  shared_preferences: any


dev_dependencies:

  flutter_test:
    sdk: flutter
  test: ^1.5.1

  flutter_launcher_icons: "^0.7.0"

flutter_icons:

  android: true
  ios: false
  image_path: "assets/icon.png"


flutter:

  uses-material-design: true

  assets:
    - sets/alpha/
    - sets/bases/
    - sets/classic/
    - sets/light/
    - sets/modern/
    - sets/nature/
    - sets/neo/
    - sets/space/
    - sets/wood/