
name: chess_umbrella
description: Play chess with multipeer connectivity

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"


dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
#  flutter_blue: ^0.5.0
  tuple: ^1.0.2


dev_dependencies:

  flutter_test:
    sdk: flutter
  test: ^1.5.1


flutter:

  uses-material-design: true

  assets:
   - sets/default/
